### ISSUE TITLE
luid-moment does not handle undefined values well

### ISSUE THREAD

**Issue by srabere** [LuccaSA/lucca-ui#104]
when the input of the hours is empty i should have my $viewvalue set to undefined

**Comment by srabere** [comment]
also set minutes to '00' on blur if hours != undefined

**Comment by srabere** [comment]
also you should set validity(pattern) to false if the user types "qsd" in one of the inputs

**Comment by lucienbertin** [comment]
@srabere : i can add `ng-invalid-hours` or `ng-invalid-minutes` if you want

`qw:12` -> `ng-valid-minutes` `ng-invalid-hours`, `$viewValue = undefined` so you can have a `ng-invalid-required also

keep in mind that on the `on-blur` of the minute inputs or the `ng-change` of the hour inputs, i'll set the minutes to `00` if hours is valid and `undefined` otherwise

**Comment by lucienbertin** [comment]
should be fixed in next release (release [2.0.6](https://github.com/LuccaSA/lucca-ui/releases/tag/2.0.6))
