### ISSUE TITLE
Core.elements.typography : link color hard coded (not in the palette)

### ISSUE THREAD

**Issue by thomaf** [LuccaSA/lucca-ui#112]
\scss\themes\default\core\elements\_typography.defaults.scss
Line 65
```sass
	links: (
		color: 					#00b2ed,
		decoration: 			none,
		hover: (
			color: 				lighten(#00b2ed, 10),
			decoration: 		underline
		),
		visited: (
			color: 				darken(#00b2ed, 10)
		)
	)
```

**Comment by bpaugam** [comment]
It can be freely overriden in a `_typography.overrides.scss` file in the `/my_theme/core/elements/` directory.

**Comment by lucienbertin** [comment]
yeah but it should be a variable right ?
```sass
$linkColor: #00b2ed;
    links: (
        color:                  $linkColor,
        decoration:             none,
        hover: (
            color:              lighten($linkColor, 10),
            decoration:         underline
        ),
        visited: (
            color:              darken($linkColor, 10)
        )
    )
```

**Comment by bpaugam** [comment]
You can't have a self-referencing variable. There's no better way to achieve that than to add this to your custom theme :

`my_theme/core/elements/_typography.overrides.scss`
```
$myTheme: (
    links: (
        color: {{myAwesomeColor}},
        hover: (
            color: {{myAwesomeHoverColor}}
        ),
        visited: (
            color: {{myAwesomeVisitedColor}}
        )
    )
);
```

**Comment by lucienbertin** [comment]
i just fiddled with it  and overriden it for figgo and realized i did not trully understand the problem, my bad on this one

it is indeed easily overridable and as the hex is just present here there is no duplication. It's like the divider color, it is not in one of the palettes because it's not its place

@thomaf I can show you how to easily override it if you want
